[workspace]
members = [
    "common/mine-with-friends-board",
    "common/attest",
    "common/attest-messages",
    "common/attest-database",
    "common/attest-util",
    "common/game-host",
    "ux/src-tauri/"
]
