[package]
name = "tor-chat"
version = "0.1.0"
edition = "2021"


[dependencies]
libtor = "=46.9.0+0.4.6.x"
tokio = { version = "1.17.0", features = ["full"] }
reqwest = {version="=0.11.10", features=["socks", "json"]}
serde_json = "1.0.79"
serde = "1.0.136"
serde_derive = "1.0.136"
ruma-signatures = "0.10.0"
ruma-serde = "0.6.0"
sqlite = "0.26.0"   
directories = "3.0.1"
rand = "0.7"
[dependencies.ed25519-dalek]
version= "1.0.1"
features=['serde']

[dependencies.sapio-bitcoin]
version = "0.28.0-rc.3"
features=['use-serde']