name: Every night, tag a nightly branch

on:
  schedule:
  - cron: '00 7 * * *'
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
  make_tag:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    name: Make a Tag.
    steps:
      - uses: actions/checkout@v2
      - name: make the tag
        run: |
          git tag "v0.0+${{ github.event.repository.updated_at}}-master-nightly"
          git push origin "v0.0+${{ github.event.repository.updated_at}}-master-nightly"
